### ISSUE TITLE
There seems to be something wrong in the help info.

### ISSUE THREAD

**Issue by csy19960309** [VR-25/tarb#3]
At the example section, if patterns have to be matched, there should not be a dot behind the flags.

**Comment by VR-25** [comment]
Could you share the specific line?

**Comment by csy19960309** [comment]
> Could you share the specific line?

https://github.com/VR-25/tarb/blob/3fcb12d8fb19405bfb568f8d473d4eb5faa3c213/tarb.sh#L532C32-L532C32

I remember having managed to match patterns after removing the dot.

**Comment by VR-25** [comment]
Ok, that's an exception. Patterns after the plus are meant for backing up system apps' data.

 While we're at it, are you unable to match system apps when a dot is present before the "+"?

**Comment by csy19960309** [comment]
> Ok, that's an exception. Patterns after the plus are meant for backing up system apps' data.
> 
> While we're at it, are you unable to match system apps when a dot is present before the "+"?

I remember that patterns after the plus backed up my user apps' data, but I am not sure if it was system data or user data because it's been a long time. But I am sure before I removed the dot nothing worked out at all.
Never mind. As I don't flash ROMs these days I cannot give more tests, please feel free to close this issue if it doesn't help for lacking details.
